name: Terraform Plan

on:
  push:
    # Runs on all branches
  pull_request:
    branches: [ main ]

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    environment: main
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Check tools
        run: |
          echo "=== System Info ==="
          uname -a
          echo "=== Available tools ==="
          which bash || echo "bash not found"
          which curl || echo "curl not found"
          which unzip || echo "unzip not found"
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ">= 1.12.0"
          
      - name: Install AWS CLI
        run: |
          if ! command -v aws &> /dev/null; then
            echo "Installing AWS CLI..."
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
            rm -rf awscliv2.zip aws/
          else
            echo "AWS CLI already installed: $(aws --version)"
          fi

      - name: Configure AWS credentials
        env:      
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
        run: |
          echo "AWS credentials configured"
          # Validate that AWS credentials are set
          if [ -z "$AWS_ACCESS_KEY_ID" ]; then
            echo "ERROR: AWS_ACCESS_KEY_ID not set"
            exit 1
          fi
          
      - name: Verify tools
        run: |
          echo "=== Terraform version ==="
          terraform version
          echo "=== AWS CLI version ==="
          aws --version
          echo "=== Ready for AWS authentication test ==="
          
      - name: AWS CLI authentication validation
        run: |
          echo "=== AWS Identity ==="
          aws sts get-caller-identity

      - name: Terraform init
        env:
          BACKEND_BUCKET: ${{ vars.TERRAFORM_STATE_BUCKET }}
          BACKEND_REGION: ${{ vars.BACKEND_REGION }}
          TF_VAR_aws_region: ${{ vars.AWS_DEFAULT_REGION }}
        run: |
          echo "=== Terraform Initialization ==="
          echo "BACKEND_BUCKET: ${BACKEND_BUCKET}"
          echo "BACKEND_REGION: ${BACKEND_REGION}"  
          echo "TF_VAR_aws_region: ${TF_VAR_aws_region}"
          terraform init \
            -backend-config="bucket=${BACKEND_BUCKET}" \
            -backend-config="key=tfstate/nullpoint-aws/${TF_VAR_aws_region}/nullpoint-aws.tfstate" \
            -backend-config="region=${BACKEND_REGION}"

      - name: Terraform plan
        env:
          TF_VAR_aws_region: ${{ vars.AWS_DEFAULT_REGION }}
        run: |
          echo "=== Terraform Plan ==="
          echo "TF_VAR_aws_region: ${TF_VAR_aws_region}"
          terraform plan