name: Terraform

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: main
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Check tools
        run: |
          echo "=== System Info ==="
          uname -a
          echo "=== Available tools ==="
          which bash || echo "bash not found"
          which curl || echo "curl not found"
          which unzip || echo "unzip not found"
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0
          
      - name: Install AWS CLI
        run: |
          if ! command -v aws &> /dev/null; then
            echo "Installing AWS CLI..."
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
            rm -rf awscliv2.zip aws/
          else
            echo "AWS CLI already installed: $(aws --version)"
          fi
          
      - name: Verify tools
        run: |
          echo "=== Terraform version ==="
          terraform version
          echo "=== AWS CLI version ==="
          aws --version
          echo "=== Ready for AWS authentication test ==="
          
      - name: AWS CLI authentication validation
        run: |
          echo "=== AWS Identity ==="
          aws sts get-caller-identity